### Just Ask for a Image

POST {{host}}/spring-ai/images/ask
Content-Type: application/json

{ "question" : "Hello, please generate an image of the USS New Jersey Warship passing the British Parliament with the word ITOPIA printed on the front of the warship's body." }

> {%
    client.log(response.status === 200);
  %}


### Test OpenAI Vision

POST {{host}}/spring-ai/images/vision
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="image_1.jpg"
Content-Type: image/jpeg

< ./image_1.jpg

--boundary--