### Test OpenAI Speech


POST {{host}}/spring-ai/speech
Content-Type: application/json
Accept: audio/mpeg

{ "question" : "In a small village nestled at the foot of a daunting mountain, lived an eternal optimist named Ellie." }