### Just Ask a Question

POST {{host}}/spring-ai/rag/ask
Content-Type: application/json
Accept: application/json

{ "question" : "Please tell me the release date, box office earnings, revenue, and runtime of ```The Lord of the Rings: The Two Towers```" }

> {%
    client.log(response.body.answer);
  %}
