### Just Ask a Question

# What is a good truck to pull a Sportsman 212 boat? Expected answer: Chevy Traverse
# What is a good truck to pull a Sportsman 232 boat? Expected answer: Chevy Colorado
# What is a good truck to pull a Sportsman 322 boat? Expected answer: Chevy 2500
# What is a good truck to pull a Scout 380 LXF boat? Expected answer: Chevy 3500 Duramax


POST {{host}}/spring-ai/rag/ask
Content-Type: application/json
Accept: application/json

{ "question" : "What is a good truck to pull a Sportsman 212 boat? " }

> {%
    client.log(response.body.answer);
  %}
