### GET all language ranges from HEADER
GET {{host}}/headers/languages/ranges
Accept-Language: en-US,en;q=0.9,fr;q=0.8,de;q=0.7,es;q=0.6

> {%
    client.test("Test the weight of Language Ranges", function () {
        client.assert(response.body.length === 5, ">>> Accept 5 languages");
        client.assert(response.body[0].range === "en-us" &&
            response.body[0].weight === 1.0, ">>> The client prefers en-US");
    });
  %}

### GET accept all locales from HEADER
GET {{host}}/headers/locales
Accept-Language: en-US,en;q=0.9,fr;q=0.8,de;q=0.7,es;q=0.6

> {%
    client.test("Test the prefer Locale of client", function () {
        client.assert(response.body.length === 5, ">>> Accept 5 languages");
        client.assert(response.body[0] === "en_US", ">>> The client prefers locale en_US");
    });
%}