spring:
  application:
    name: spring-ai-rag
  ai:
    openai:
      # Pass API key as environment variable, e.g. -DOPENAI_API_KEY=your-api-key
      api-key: ${OPENAI_API_KEY}
sfg:
  aiapp:
    # vectorStorePath: "C:\\dev\\ai\\data\\vectorstore.json"
    vectorStorePath: ${VECTOR_STORE_PATH}
    documentsToLoad:
      - classpath:/movies500.csv