spring:
  application:
    name: spring-ai-rag
  ai:
    openai:
      # Pass API key as environment variable, e.g. -DOPENAI_API_KEY=your-api-key
      api-key: ${OPENAI_API_KEY}
sfg:
  aiapp:
    vectorStorePath: "C:\\Users\\yul\\AppData\\Local\\Temp\\vectorstore.json"
    documentsToLoad:
      - classpath:/movies500.csv