spring:
  application:
    name: spring-ai-functions
  ai:
    openai:
      # Pass API key as environment variable, e.g. -DOPENAI_API_KEY=your-api-key
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4
