spring:
  datasource:
    url: jdbc:postgresql://localhost:54315/yulikexuan?currentSchema=spring_db_test
    username: postgres
    password: tecsys
  sql:
    init:
      mode: always
  flyway:
    enabled: true
    location: classpath:db/migration
    # baseline-on-migrate: true
    default-schema: "spring-db-test"
