### Just Ask a Question about the current weather of a city


POST {{host}}/spring-ai/functions/weather
Content-Type: application/json
Accept: application/json

{ "question" : "What is the weather in Saint-Laurent, Quebec, Canada? " }

> {%
    client.log(response.body.answer);
  %}
