### Just Ask a Question

POST {{host}}/spring-ai/rag/ask
Content-Type: application/json
Accept: application/json

{ "question" : "Hi, do you have any suggestion about Choose a Vector Database working with Spring AI? Please make your answer output has 80 charactors length per line." }

> {%
    client.log(response.body.answer);
  %}
